### PR TITLE
Added project copy functionality

### LINKED ISSUE #265: Add Button to Copy Projects in UI
As part of 3blades/3blades/#133, when viewing a project there should be a button that allows the user to copy the project they are viewing to their own workspace. This requires 3blades/app-backend#408 and the accompanying documentation to be completed first.

### PR DESCRIPTION
**Pull request by raygesualdo**
Closes #265.

```
feat: issue #265 - added project copy functionality
```

project-copy

### CODE REVIEW

**Comment by jgwerner** [comment]
@raygesualdo can user confirm the name for the copied project? The animated gif shows a random string for the project name.

**Comment by raygesualdo** [comment]
@jgwerner we decided for this first pass we wouldn't give them the option. The only time a value is appended to the current name is when there's a collision. That being said, the current collision prevention scheme isn't exactly what I expected. 

@johngriebel was it always going to be a timestamp appended to duplicate project names?

**Comment by jgwerner** [comment]
@johngriebel @raygesualdo I did talk to John about this and gave him my feedback. I think the scheme is perfectly suited to avoid collisions. But, I don't think it offers a good user experience. If the user has to navigate to a random project name then that would create issues. Wouldn't it be better to set the random name as a project attribute and leave a friendly name instead? GitHub simply appends a `-(int)` when there is a duplicate repo name. I've seen others that append `(Copy)`.

**Comment by jgwerner** [comment]
@raygesualdo @johngriebel side note: perhaps its time to start mocking UI behavior before throwing code at it, just to make sure we are in-line. Seems like we didn't spec this correctly and some rework may be required.

**Comment by johngriebel** [comment]
I'll change it to an intern instead of a timestamp. Not really a UI issue.

**Pull request merged**
