### PR TITLE
Implemented code splitting and other performance enhancements

### LINKED ISSUE #125: Implement code splitting
### Why
This will allow for more efficient bundling and asset delivery to the customer.

### What
We will implement code splitting in Webpack via config changes and dynamic imports.

### How 
Shortest path seems to be doing `import()`s on routes. [react-loadable](https://github.com/thejameskyle/react-loadable/) seems widely regarded as the solution for dynamically importing components. Combine that with [this developer's experience](https://twitter.com/matzatorski/status/872059865350406144) and it looks fairly straightforward. 

**Additional Reading**
- [Vendor and code spitting in Webpack 2](https://medium.com/@adamrackis/vendor-and-code-splitting-in-webpack-2-6376358f1923)
- [SurviveJS: Code Splitting](https://survivejs.com/webpack/building/code-splitting/)
- [Dynamic Vendor Bundling in Webpack](https://jeremygayed.com/dynamic-vendor-bundling-in-webpack-528993e48aab)

### PR DESCRIPTION
**Pull request by raygesualdo**
Closes #125.

### CODE REVIEW

**Comment by raygesualdo** [comment]
To show how much of a change this is, I opened the Chrome DevTools, disabled all caching, artificially limited the network connection, and loaded up both dev on CloudFront and my local branch (the one with performance changes) on Now. The results of multiple runs will be included below with a breakdown of before load times, after load times, and deltas.

**Comment by raygesualdo** [comment]
**Good 3G (40ms, 1.5Mb/s, 750kb/s)**

Before:
3g-before

After:
3g-after

Before Load Time: `24.31s`
After Load Time: `3.08s`
Speed Savings: `21.23s`/`87.3%`

**Comment by raygesualdo** [comment]
**DSL (5ms, 2.0Mb/s, 1.0Mb/s)**

Before:
dsl-before

After:
dsl-after

Before Load Time: `19.13s`
After Load Time: `2.96s`
Speed Savings: `16.17s`/`84.5%`

**Comment by raygesualdo** [comment]
**WiFi (2ms, 30Mb/s, 15Mb/s)**

Before:
wifi-before

After:
wifi-after

Before Load Time: `4.16s`
After Load Time: `1.39s`
Speed Savings: `2.77s`/`66.6%`

**Comment by raygesualdo** [comment]
**Unthrottled**

*Note: My internet speeds unthrottled are 120Mb/s, 10Mb/s*

Before:
unthrottled-before

After:
unthrottled-after

Before Load Time: `3.51s`
After Load Time: `1.14s`
Speed Savings: `2.37s`/`67.5%`

**Comment by jgwerner** [comment]
@raygesualdo that's quite the improvement. Would new versions of the front end require new downloads? I would assume so, since there is a build.

**Comment by raygesualdo** [comment]
@jgwerner I'm not sure I understand your question.

**Comment by jgwerner** [comment]
@raygesualdo what I mean is if a new build is deployed it would be considered a fresh download into the browser. Correct?

**Comment by raygesualdo** [comment]
We discussed offline, but I'll summarize here as well. With "vanilla" Webpack code splitting, the entire set of files would need to be re-downloaded by the client every time we do a new deploy. However, the way this PR is configured, each chunk has a deterministic hash in its file name, so only chunks that have changed between builds would need to be re-downloaded by the client.

**Pull request merged**
